spring:
  application:
    name: 022_twentysecond-hw

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_pet
    username: postgres
    password: PosTer231

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    org.flywaydb: DEBUG

