CREATE TABLE IF NOT EXISTS Sensor
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar not null
);

CREATE TABLE IF NOT EXISTS Measurement
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value      real      not null,
    raining    boolean   not null,
    created_at timestamp not null,
    sensor_id  int references Sensor (id)
)