version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app_server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_server:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=PosTer231
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - "8080:8080"
    depends_on:
      - db_server

  db_server:
    image: postgres:16
    container_name: db_server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PosTer231
    volumes:
      - /server_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db: null
